var fs = require("fs");
var path = require("path");
var request = require("request");

//创建文件夹目录
var dirPath = path.join(__dirname, "file");
if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath);
    console.log("文件夹创建成功");
} else {
    console.log("文件夹已存在");
}


var filelist = [
    "http://zhufengpeixun.com/jg-vue/vue-analyse/source.html",
    "http://zhufengpeixun.com/jg-vue/assets/css/0.styles.ae591a53.css",
    "http://zhufengpeixun.com/jg-vue/assets/js/app.d8ef08ae.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/2.7293552a.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/70.b1749499.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/10.807c9275.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/11.eeda623b.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/12.ccb84231.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/13.bbf53006.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/14.25dd5178.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/15.4a4c3fec.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/16.d574c6c2.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/17.eb6dc1d2.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/18.edb55f0c.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/19.f1a89ef4.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/20.53afb9f0.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/21.059498af.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/22.75982deb.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/23.aa4f7f38.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/24.06578636.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/25.96684f2f.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/26.a0d8257e.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/27.28f9145f.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/28.604f0820.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/29.03d7a448.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/3.e2ce560a.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/30.b372f258.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/31.91fff919.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/32.e464c8a3.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/33.8e929533.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/34.7d597ded.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/35.8b8b0221.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/36.98723348.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/37.9546f1e9.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/38.9d3f524b.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/39.c7c89f49.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/4.9330327c.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/40.664fd90f.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/41.7a636566.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/42.6f44aeba.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/43.bdea7a2c.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/44.354df2ec.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/45.ec51b078.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/46.1e4fceaa.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/47.b83f1f33.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/48.870e54a3.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/49.aed7e317.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/5.dff32249.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/50.b25c0a2a.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/51.c6fdf98b.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/52.cceab9e8.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/53.38b87563.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/54.665af34b.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/55.b127c7d2.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/56.d5f7f773.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/57.2a055f60.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/58.cb27c047.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/59.a5a2c5bc.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/6.744c61ec.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/60.b1b55bc3.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/61.036c041c.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/62.2a83e9df.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/63.9e13dd57.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/64.ee062540.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/65.e44fddf4.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/66.be4409a4.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/67.702521b8.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/68.01d97b42.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/69.c9e9b976.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/7.9e30e5c0.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/71.cfb9cf5a.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/72.af1e446b.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/73.a16a8415.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/74.1cedcea2.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/75.2fd6019c.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/76.8160e9ab.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/77.2e9331e9.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/78.40771614.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/79.bfd5166e.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/8.14f387ee.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/80.473c9b7f.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/81.b3d53b09.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/82.f7f9af36.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/83.f21aea37.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/84.f50fee1e.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/85.6b6660bc.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/86.d1a59392.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/87.2ec23583.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/88.35106516.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/89.29c7e34d.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/9.2915923f.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/90.f54351fd.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/91.6bd6145d.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/92.9db4f8c9.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/93.745dde01.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/94.c37de3b5.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/95.97f4e5c1.js",
    "http://zhufengpeixun.com/jg-vue/assets/js/96.0f2c1c5e.js",

    "http://zhufengpeixun.com/jg-vue/vue-analyse/note-1.html",
    "http://zhufengpeixun.com/jg-vue/vue-apply/note-1.html",
    "http://zhufengpeixun.com/jg-vue/node/async-1.html",
    "http://zhufengpeixun.com/jg-vue/typescript/1.html",
    "http://zhufengpeixun.com/jg-vue/vue3/1.html",
    "http://zhufengpeixun.com/jg-vue/opt/note.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/watch-computed.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/web-component.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/component.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/pwa.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/diff.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/note-2.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/note-3.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/note-4.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/vuex.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/vue-ssr.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/cli.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/introduce.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/reactivity.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/vue3-diff.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/vite.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/custom-render.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/async.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/initial.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/compileToFunction.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/from0.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/mic-front1.html",
    "http://zhufengpeixun.com/jg-vue/vue-analyse/mic-front2.html",

    "http://zhufengpeixun.com/jg-vue/assets/img/entry.fd620404.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/shadow-dom.4d23a921.png",

    "http://zhufengpeixun.com/jg-vue/assets/img/vue-diff.4c21677d.jpg",
    "http://zhufengpeixun.com/jg-vue/assets/img/object.a0219fcb.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/array.f59c87c8.png",

    "http://zhufengpeixun.com/jg-vue/assets/img/loop.1db11d95.jpg",
    "http://zhufengpeixun.com/jg-vue/assets/img/ssr.29164cfb.png",


    "http://zhufengpeixun.com/jg-vue/assets/img/jiegou.93536c0b.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/diif-1.ab276421.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/diif-2.7a09a836.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/diif-3.633a1a31.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/diif-4.d3e4a7df.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/diif-5.747209db.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/diif-6.07076735.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/diif-7.92c37bd1.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/diif-8.58f193d3.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/diif-9.566dc6f6.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/diif-11.7a5f3848.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/diif-12.03470ece.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/diif-13.74cef58e.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/diif-10.c30e8387.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/diff-14.7e364371.png",

    "http://zhufengpeixun.com/jg-vue/assets/img/bing.e3fa347f.gif",
    "http://zhufengpeixun.com/jg-vue/assets/img/1.9d32f541.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/2-1595654633394.9f5b715a.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/4-1595654810986.1b94a808.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/lifecycle.fb2af586.png",
    "http://zhufengpeixun.com/jg-vue/assets/img/flow.7557f3a1.png"

]

//循环多线程下载
for (let i = 0; i < filelist.length; i++) {
    let fileName = filelist[i].replace("http://zhufengpeixun.com", "")
    let url = filelist[i]
    let stream = fs.createWriteStream(path.join(dirPath, fileName));
    request(url).pipe(stream).on("close", function (err) {
        console.log("文件[" + fileName + "]下载完毕");
    });
}

